[package]
name = "rust-patterns"
version = "0.0.0"
authors = ["Alexander Smoktal <cosm.ua@gmail.com>"]
license = "MIT"

[dependencies]

[[bin]]
name = "abstract_factory"
path = "src/creational/abstract_factory.rs"

[[bin]]
name = "builder"
path = "src/creational/builder.rs"